const USER_NOT_FOUND_ERR = 1;
const USER_DEACTIVATION_ERR = 2;
const USER_ACTIVATION_ERR = 3;
const USER_ALREADY_CREATED = 4;
const USER_ALREADY_DEACTIVATED = 5;
const USER_ALREADY_ACTIVATED = 6;
const USER_ALREADY_DELETED = 7;

const ADMIN_NOT_FOUND_ERR = 8;

const INTERNAL_ERR = 10;

const INSUFFICIENT_AMOUNT_ERR = 11;
const SAME_USER_ERR = 12;
const SENDER_NOT_FOUND_ERR = 13;
const RECEIVER_NOT_FOUND_ERR = 14;
const WITHDRAW_ERR = 15;
const DEPOSIT_ERR = 16;
const ACCESS_DENIED_ERR = 17;

export {
  USER_NOT_FOUND_ERR,
  USER_DEACTIVATION_ERR,
  USER_ACTIVATION_ERR,
  USER_ALREADY_CREATED,
  USER_ALREADY_DEACTIVATED,
  USER_ALREADY_ACTIVATED,
  USER_ALREADY_DELETED,
  ADMIN_NOT_FOUND_ERR,
  INTERNAL_ERR,
  INSUFFICIENT_AMOUNT_ERR,
  SAME_USER_ERR,
  SENDER_NOT_FOUND_ERR,
  RECEIVER_NOT_FOUND_ERR,
  WITHDRAW_ERR,
  DEPOSIT_ERR,
  ACCESS_DENIED_ERR,
};
